services:
  - type: web
    name: elite-glam-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000

# MongoDB database configuration
databases:
  - name: mongodb
    databaseName: eliteglam
    user: eliteglam_user